services:
  xanny-go-template:
    container_name: xanny-go-template
    build:
      context: .
      dockerfile: Dockerfile
    image: "xanny-go-template:1.0.4"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${PORT}:${PORT}"